### PR TITLE
add nightly CI for installation user stories

### PR DESCRIPTION
**Pull request by rhelmot**
Fish wanted CI for https://github.com/angr/angr/pull/4857 but it's not something we can test without a separate installation pass, so I put it here.

### CODE REVIEW

**Comment by twizmwazin** [comment]
I don’t know exactly how opentelemetry works, but would it not be possible to install the dependency in the CI, activate it at the start of a specific test, and then retrieve the output to validate at the end of the test?

**Comment by ltfish** [comment]
@twizmwazin We would like to test that OpenTelemetry is not installed and not required unless the user opts in. This gives our users the confidence that we do not collect any information by default.

**Comment by twizmwazin** [comment]
I see. Maybe an alternative is setting up an environment like with the windows/macos smoke tests and then only running the telemetry test there? Or better yet also add a no-telemetry test case that runs in the main CI to ensure that it doesn’t log anything by default, if that’s possible?

**Comment by rhelmot** [comment]
The no-telemetry test would be a bit superfluous since the code is being exercised constantly, and in order to connect "the other end" of the telemetry pipe we would need to install the dependency which triggers the telemetry to activate.

I would rather have this very under-specified environment (matrix-tested across platforms?) to test specific user stories for installations that we want to make sure work.

**Review by twizmwazin — APPROVED** [review]

**Pull request merged**
