### PR TITLE
Paper cut: -n == don't ask for github usernames and passwords

### PR DESCRIPTION
**Pull request by Jacopo**
Clean-ish option to get rid of the http password prompts.

### CODE REVIEW

**Comment by rhelmot** [comment]
Wait it's that easy???????? What the heck??? is this a recent git change or have we just been chumps for the past 4 years?

**Comment by rhelmot** [comment]
If this is a standard git option I'm honestly going to say that we should make this the default, since nobody has ever tried to install angr from a private repo without an ssh key associated

**Comment by Jacopo** [comment]
Or, you haven't had to work extensively with Android's repo :)
I will share more lore at defcon :D

**Comment by Jacopo** [comment]
Of course, the secret repos are ssh-only. I approve :D
Then I guess you may just export GIT_ASKPASS=true at the very top and that's it

**Pull request closed without merging**
