### PR TITLE
Small edit for setup.sh

### PR DESCRIPTION
**Pull request by tiffanyb**
To improve for the case that someone (yeah it is me) re-setups angr environment by angr-dev.

### CODE REVIEW

**Comment by rhelmot** [comment]
Do we actually want to install bpython by default? We recommend using IPython several times in the docs, but never bpython. My experience with it was that it's very good and very powerful, but if you're used to IPython it might trip people up a big.

**Comment by ltfish** [comment]
I would say we stick to `ipython` by default. People can freely choose whatever interactive shell they are comfortable with.

**Comment by tiffanyb** [comment]
I am fine with setting `ipython` by default. will change it.

**Comment by ltfish** [comment]
Thanks!

**Pull request merged**
