### PR TITLE
Clean up admin directory

### PR DESCRIPTION
**Pull request by twizmwazin**
These scripts haven't been used for quite a while now.

### CODE REVIEW

**Comment by rhelmot** [comment]
checkout_at.py and blame.sh are still pretty important.

**Comment by ltfish** [comment]
We definitely need `checkout_at.py` and `blame.sh`. Not sure about other scripts, but some of them are definitely no longer relevant.

@zardus Do you see any scripts that we must keep around?

**Comment by twizmwazin** [comment]
For blame.sh, would [gitmailmap](https://git-scm.com/docs/gitmailmap) be a preferable solution, especially since it would apply across all git commands and can be configured to be used automatically?

**Comment by rhelmot** [comment]
The purpose of blame.sh is not to do mailmapping but rather to do cumulative line number counting across multiple repositories.

**Comment by twizmwazin** [comment]
Oh I see, apologies

**Comment by twizmwazin** [comment]
Two scripts mentioned are retained and comments added to explain functionality, other scripts have been pruned.

**Review by rhelmot — APPROVED** [review]

**Pull request merged**
