### PR TITLE
setup.bat: pip install updated capstone and unicorn

### PR DESCRIPTION
**Pull request by 0xbc**
Running setup.bat with the modification in this PR runs cleanly for me with:
- Windows 10 (EDIT - also works on Win7)
- VS2015 developer prompt
- Clean, empty virtualenv
- Python 2.7 32-bit installed and on the `PATH`
- ~~~Cygwin installed, with `cpp`, and `cmake`, on the `PATH` (after Python)~~~ (EDIT - Cygwin not required, see comments below)

~~~I'm unsure if `g++` is also a requirement still in Cygwin - I've got it installed but didn't check under the hood whether anything was using it to build things.~~~ (EDIT - Cygwin not required).

### CODE REVIEW

**Comment by rhelmot** [comment]
Merging this is gonna require a little more careful looking on my part - that file powers our appveyor CI, which is currently broken for other reasons I haven't had a chance to look at.

I'm confused about the cygwin part, though - all the build steps for angr *should* work with visual studio.

**Comment by 0xbc** [comment]
Oh... I thought there was something (pyvex?) that required `cpp` to build -
maybe not? I'll test building it again sans Cygwin.

**Comment by rhelmot** [comment]
mm... it looks in the CPP environment variable to try to figure out which preprocessor to use, but without it it'll try `cpp`, `cc -E`, and `cl /E`. The last one should work in VS.

**Comment by 0xbc** [comment]
Got the following breakage building pyvex:
```Creating CFFI defs file
No handlers could be found for logger "cffier"
Exception('Couldn\'t process pyvex headers.Please set CPP environmental variable to local path of "cpp".Note that "cpp" and "g++" are different.',)
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    'pyvex': ['lib/*', 'include/*']
  File "c:\python27\Lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\python27\Lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\python27\Lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 112, in run
    self.execute(_build_ffi, (), msg="Creating CFFI defs file")
  File "c:\python27\Lib\distutils\cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "c:\python27\Lib\distutils\util.py", line 309, in execute
    func(*args)
  File "setup.py", line 90, in _build_ffi
    make_ffi.doit(os.path.join(VEX_PATH,'pub'))
  File "c:\src\angr-dev-again\pyvex\make_ffi.py", line 88, in doit
    "Note that \"cpp\" and \"g++\" are different."
Exception: Couldn't process pyvex headers.Please set CPP environmental variable to local path of "cpp".Note that "cpp" and "g++" are different.
```
The problem is the condition for detecting errors is being met when it's not intended to in pyvex's `make_ffi.py` on line 75:
```
if p.returncode != 0 or stderr or not header:
```
For me, `cl` is printing the compiler version string to stderr:
```
In [1]: stderr
Out[1]: 'Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86\r\nCopyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\npyvex.h\r\n'
```
If I just delete the `or stderr` clause then it builds fine... not sure if that patch would break other tools though?

**Comment by 0xbc** [comment]
(sorry, clicked close-and-comment by mistake)

**Comment by 0xbc** [comment]
btw besides pyvex, everything else seems to have built fine sans Cygwin. 👍

**Pull request closed without merging**
