### PR TITLE
setup.sh now depends on libcapstone3.

### PR DESCRIPTION
**Pull request by gynophage**
Trusty doesn't provide libcapstone3. Update to wily. apt-get install libcapstone3.

### CODE REVIEW

**Comment by zardus** [comment]
Hello,

We'd prefer to stay on an LTS version of Ubuntu. libcapstone3 shouldn't be
necessary, as pip builds capstone during installation.

**Comment by gynophage** [comment]
Should I create a pull request for setup.sh then? libcapstone3 is in the DEBS requirements, which breaks docker build.

**Comment by zardus** [comment]
Actually, let me make sure it actually builds as is....

**Comment by zardus** [comment]
Oh, interesting... That should be fixed as of adcdf67fc2425ac1e1568e72e548eb27e779f55f, though I'd forgotten to actually push that to github until yesterday or the day before. Could you check if you're running the latest version?

**Comment by gynophage** [comment]
I didn't pull before making this pull request - so I was a little out of date. Latest works. Sorry for bothering you!

**Comment by zardus** [comment]
No worries! Like I said, I'd forgotten to push that fix until recently :-)

**Comment by zardus** [comment]
Also, the interesting thing is that that *used* to work, so libcapstone3 must have disappeared from trusty at some point. I wonder why...

**Pull request closed without merging**
