### PR TITLE
Add Arch-Linux support to setup.sh script

### PR DESCRIPTION
**Pull request by m1ghtym0**

### CODE REVIEW

**Comment by m1ghtym0** [comment]
Omg, didn't check PR's before doing this, apparently https://github.com/angr/angr-dev/pull/5
has done the same... m)

**Comment by zardus** [comment]
These changes seem more minimalistic, and #5 conflicts with the current tree, so I'm down to go with this one. Can you rebase this on top of the current master so that the CI runs?

**Comment by m1ghtym0** [comment]
Here you go:-)

**Comment by zardus** [comment]
Thanks!

**Pull request merged**
