### PR TITLE
Adding angr-targets

### PR DESCRIPTION
**Pull request by bannsec**
Adding angr-targets to setup

### CODE REVIEW

**Comment by bannsec** [comment]
Went ahead and added archr too.

**Comment by rhelmot** [comment]
angr-targets depends on avatar2 and archr depends on shellphish_qemu, both of which are amd64 only. I don't think this is a good idea as it will lock us to development on amd64 architectures. Yes realistically I know this isn't a big deal but given the fact that you can't even build those packages from source it makes me uncomfortable.

**Comment by bannsec** [comment]
Gotcha. Would it make more sense to integrate those packages into Mechaphish repo?

**Comment by rhelmot** [comment]
I actually changed my mind about these. We should just clone those repos and be done with it. I'll reapply this commit since we've added conflicts since this PR was made.

**Pull request closed without merging**
